apiVersion: v1
kind: Service
metadata:
  name: flask-demo-app
  namespace: monitoring
  labels:
    app: flask-demo-app
spec:
  type: NodePort
  selector:
    app: flask-demo-app
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
    nodePort: 30081
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-demo-app-monitor
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  selector:
    matchLabels:
      app: flask-demo-app
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
  namespaceSelector:
    matchNames:
      - monitoring  # or your app's namespace
