{
 "title": "Awesome dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Flask App Total Clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "demo_app_clicks_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Flask App Toggle status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "targets": [
    { "expr": "demo_app_enabled", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Flask App Toggle status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "demo_app_enabled", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Flask App Random values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "demo_app_random_values", "legendFormat": "{{job}} random" }
   ]
  }
 ]
}